// src/themes/themeContract.css.js
import { createThemeContract } from '@vanilla-extract/css';
import { blackA, whiteA } from '@spiffdog/spiffy-colors';

const defaultColors = {
  1: '',
  2: '',
  3: '',
  4: '',
  5: '',
  6: '',
  7: '',
  8: '',
  9: '',
  10: '',
  11: '',
  12: '',
};

const paletteColorsBase = {
  amber: {...defaultColors},
  blue: {...defaultColors},
  bronze: {...defaultColors},
  brown: {...defaultColors},
  crimson: {...defaultColors},
  cyan: {...defaultColors},
  gold: {...defaultColors},
  grass: {...defaultColors},
  gray: {...defaultColors},
  green: {...defaultColors},
  indigo: {...defaultColors},
  iris: {...defaultColors},
  jade: {...defaultColors},
  lime: {...defaultColors},
  mauve: {...defaultColors},
  mint: {...defaultColors},
  olive: {...defaultColors},
  orange: {...defaultColors},
  pink: {...defaultColors},
  plum: {...defaultColors},
  purple: {...defaultColors},
  red: {...defaultColors},
  ruby: {...defaultColors},
  sage: {...defaultColors},
  sand: {...defaultColors},
  sky: {...defaultColors},
  slate: {...defaultColors},
  teal: {...defaultColors},
  tomato: {...defaultColors},
  violet: {...defaultColors},
  yellow: {...defaultColors},
}
const paletteColorsAlpha = {
  amberA: {...defaultColors},
  blueA: {...defaultColors},
  bronzeA: {...defaultColors},
  brownA: {...defaultColors},
  crimsonA: {...defaultColors},
  cyanA: {...defaultColors},
  goldA: {...defaultColors},
  grassA: {...defaultColors},
  grayA: {...defaultColors},
  greenA: {...defaultColors},
  indigoA: {...defaultColors},
  irisA: {...defaultColors},
  jadeA: {...defaultColors},
  limeA: {...defaultColors},
  mauveA: {...defaultColors},
  mintA: {...defaultColors},
  oliveA: {...defaultColors},
  orangeA: {...defaultColors},
  pinkA: {...defaultColors},
  plumA: {...defaultColors},
  purpleA: {...defaultColors},
  redA: {...defaultColors},
  rubyA: {...defaultColors},
  sageA: {...defaultColors},
  sandA: {...defaultColors},
  skyA: {...defaultColors},
  slateA: {...defaultColors},
  tealA: {...defaultColors},
  tomatoA: {...defaultColors},
  violetA: {...defaultColors},
  yellowA: {...defaultColors},
}

export const theme = createThemeContract({
  colors: {
    solid: {
      alert: {...defaultColors},
      base: {...defaultColors},
      primary: {...defaultColors},
      success: {...defaultColors},
      warning: {...defaultColors},
    },
    alpha: {
      alert: {...defaultColors},
      base: {...defaultColors},
      primary: {...defaultColors},
      success: {...defaultColors},
      warning: {...defaultColors},
    },
    palette: {
      ...paletteColorsBase, 
      ...paletteColorsAlpha,
      blackA, 
      whiteA
    },
  },
});